# Generated by Django 5.2.6 on 2026-02-20 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('score_express', models.IntegerField(default=0)),
                ('score_complet', models.IntegerField(default=0)),
                ('score_total', models.IntegerField(default=0)),
                ('niveau', models.CharField(blank=True, max_length=20)),
                ('taille', models.CharField(blank=True, max_length=40)),
                ('secteur', models.CharField(blank=True, max_length=50)),
                ('priorite', models.CharField(blank=True, max_length=50)),
                ('reponses_express', models.JSONField(blank=True, default=dict)),
                ('reponses_complet', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='diagnosticcompletpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='diagnosticexpresspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='diagnosticrdvpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='diagnosticresultatpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='rdvrequest',
            name='submission',
        ),
        migrations.DeleteModel(
            name='CaptureLeadPage',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='DiagnosticCompletPage',
        ),
        migrations.DeleteModel(
            name='DiagnosticExpressPage',
        ),
        migrations.DeleteModel(
            name='DiagnosticRdvPage',
        ),
        migrations.DeleteModel(
            name='DiagnosticResultatPage',
        ),
        migrations.DeleteModel(
            name='DiagnosticSubmission',
        ),
        migrations.DeleteModel(
            name='RdvRequest',
        ),
    ]
