# Generated by Django 5.2.6 on 2026-02-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('entreprise', models.CharField(blank=True, max_length=160)),
                ('prefere_whatsapp', models.BooleanField(default=False)),
                ('q1_secteur', models.CharField(blank=True, max_length=50)),
                ('q2_taille', models.CharField(blank=True, max_length=50)),
                ('q3_fonction', models.CharField(blank=True, max_length=50)),
                ('q4_urgence', models.CharField(blank=True, max_length=50)),
                ('q5_donnees', models.CharField(blank=True, max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('niveau', models.CharField(blank=True, max_length=30)),
                ('estimation_gain', models.CharField(blank=True, max_length=60)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_campaign', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
