# Generated by Django 5.2.6 on 2026-02-20 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_diagnosticlead_remove_formfield_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('objectif', models.CharField(blank=True, max_length=100)),
                ('probleme_principal', models.CharField(max_length=160)),
                ('outils_actuels', models.CharField(blank=True, max_length=160)),
                ('statut', models.CharField(default='nouveau', max_length=30)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='diagnostic.diagnosticlead')),
            ],
        ),
    ]
