# Generated by Django 5.2.6 on 2026-02-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_planactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticlead',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
