# Generated by Django 5.2.6 on 2026-02-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_captureleadpage_from_address_captureleadpage_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdvRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=40)),
                ('creneau', models.CharField(max_length=80)),
                ('canal', models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('visio', 'Visio')], default='appel', max_length=30)),
                ('besoin', models.TextField(blank=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdvs', to='diagnostic.diagnosticsubmission')),
            ],
        ),
    ]
