# Generated by Django 5.2.6 on 2026-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_rdvrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticrdvpage',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='Si renseigné, on affiche Calendly (embed).'),
        ),
        migrations.AddField(
            model_name='diagnosticrdvpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
