# Generated by Django 5.2.6 on 2026-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_diagnosticrdvpage_calendly_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='c1_risque_erreur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='c2_pertes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='c3_stockage_data',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='c4_usage_ia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='c5_objectif',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='c6_frequence_reporting',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='c7_priorite_process',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticsubmission',
            name='complet_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diagnosticsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='diagnosticsubmission',
            name='nom',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
