# Generated by Django 5.2.6 on 2026-02-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0006_diagnosticsubmission_c1_risque_erreur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaptureLeadFormField',
            new_name='FormField',
        ),
    ]
