# Generated by Django 5.2.6 on 2026-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='requires_login',
            field=models.BooleanField(default=False, help_text="Visible uniquement si l'utilisateur est connecté"),
        ),
    ]
