# Generated by Django 5.2.6 on 2026-02-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_requires_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='requires_login',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='visibility',
            field=models.CharField(choices=[('all', 'Toujours visible'), ('auth', 'Visible si connecté'), ('anon', 'Visible si non connecté')], default='all', help_text="Contrôle l'affichage selon l'état de connexion", max_length=10),
        ),
    ]
