# Generated by Django 5.2.6 on 2025-09-26 11:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_homepage_body_remove_homepage_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='actualites',
            field=wagtail.fields.StreamField([('actu', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']})}),
        ),
    ]
