# Generated by Django 5.2.6 on 2026-02-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_homepage_actualites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Bienvenue', max_length=255),
        ),
    ]
