# Generated by Django 5.2.6 on 2026-02-08 08:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_homepage_hero_title'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='gouvernance',
            new_name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='actualites',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='historique',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='medias',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='vision',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 0), ('rich_text', 1), ('cta', 7), ('services', 12), ('cards', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('label', 4), ('page', 5), ('url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nom d’icône (ex: fa-solid fa-gear)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('icon', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 8), ('text', 9), ('image', 13), ('page', 5), ('url', 6)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
