# Generated by Django 5.2.6 on 2026-02-15 18:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_gouvernance_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 0), ('rich_text', 1), ('cta', 6), ('services', 13), ('cards', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'En savoir plus', 'max_length': 50}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 2), ('button_label', 3), ('page', 4), ('url', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Nos services', 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classe icône (ex: fa-solid fa-gear) ou nom d’icône.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('icon', 10), ('link_page', 4), ('link_url', 5)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 12, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('heading', 7), ('intro', 2), ('items', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Nos cartes', 'max_length': 120, 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('image', 15), ('link_page', 4), ('link_url', 5)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'max_num': 12, 'min_num': 1}), 18: ('wagtail.blocks.StructBlock', [[('heading', 14), ('intro', 2), ('items', 17)]], {})}),
        ),
    ]
