# Generated by Django 5.2.6 on 2026-02-18 11:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_homepage_body'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('duree', models.CharField(max_length=50)),
                ('public_cible', models.CharField(max_length=255)),
                ('objectif', wagtail.fields.RichTextField(blank=True)),
                ('programme', wagtail.fields.RichTextField(blank=True)),
                ('niveau', models.CharField(choices=[('decouverte', 'Découverte'), ('pratique', 'Pratique'), ('technique', 'Technique'), ('expert', 'Expert')], max_length=50)),
                ('modalite', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], default='presentiel', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormationsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
