# Generated by Django 5.2.6 on 2026-02-18 11:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_formationpage_formationsindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 0), ('rich_text', 1), ('cta_simple', 7), ('services', 14), ('cards', 19), ('cta', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('label', 4), ('page', 5), ('url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Nos services', 'max_length': 120, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.TextBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classe icône (ex: fa-solid fa-gear) ou nom d’icône.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('icon', 11), ('link_page', 5), ('link_url', 6)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'max_num': 12, 'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('heading', 8), ('intro', 3), ('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Nos cartes', 'max_length': 120, 'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('image', 16), ('link_page', 5), ('link_url', 6)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'max_num': 12, 'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('heading', 15), ('intro', 3), ('items', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'En savoir plus', 'max_length': 50}), 21: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('button_label', 20), ('page', 5), ('url', 6)]], {})}),
        ),
    ]
