# Generated by Django 5.2.6 on 2026-02-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_homepage_body'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationpage',
            name='cta_label',
            field=models.CharField(blank=True, default='Demander cette formation', max_length=80),
        ),
        migrations.AddField(
            model_name='formationpage',
            name='cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='formationpage',
            name='cta_url',
            field=models.URLField(blank=True),
        ),
    ]
