# Generated by Django 5.2.6 on 2026-02-19 13:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_formationpage_cta_label_formationpage_cta_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationpage',
            name='prerequis',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
