# Generated by Django 5.2.6 on 2026-02-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_formationpage_prerequis'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='hero_alt',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='show_toc',
            field=models.BooleanField(default=True, help_text='Afficher le sommaire automatique (H2)'),
        ),
    ]
