# Generated by Django 5.2.6 on 2026-02-19 20:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_standardpage_hero_alt_standardpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationpage',
            name='inclus',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optionnel : ce qui est inclus (supports, attestation, coaching, etc.)'),
        ),
        migrations.AddField(
            model_name='formationpage',
            name='prix_entreprise',
            field=models.CharField(blank=True, help_text='Ex: 2 200 000 FCFA ou Sur devis', max_length=50),
        ),
        migrations.AddField(
            model_name='formationpage',
            name='prix_individuel',
            field=models.CharField(blank=True, help_text='Ex: 150 000 FCFA', max_length=50),
        ),
    ]
