# Generated by Django 5.2.6 on 2026-02-21 08:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_formationsindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationsindexpage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraphe', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
