# Generated by Django 5.2.6 on 2026-02-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_formationsindexpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationsindexpage',
            name='body',
        ),
    ]
