# Generated by Django 5.2.6 on 2026-02-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_formationsindexpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationsindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FormationPage',
        ),
        migrations.DeleteModel(
            name='FormationsIndexPage',
        ),
    ]
