# Generated by Django 5.2.6 on 2026-02-21 22:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_formationsindexpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_promise',
            field=wagtail.fields.StreamField([('promise_card', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': '🚀', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Votre performance commence par vos données', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Nous construisons des systèmes mesurables et automatisés : du diagnostic jusqu’au déploiement.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Comprendre', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'audit & données', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Construire', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'apps & outils', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Automatiser', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'process & IA', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Optimiser', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'KPI & perf', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Demander un diagnostic', 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Réponse rapide • Offre adaptée à votre contexte', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('text', 2), ('step_1_title', 3), ('step_1_text', 4), ('step_2_title', 5), ('step_2_text', 6), ('step_3_title', 7), ('step_3_text', 8), ('step_4_title', 9), ('step_4_text', 10), ('button_label', 11), ('button_page', 12), ('button_url', 13), ('footnote', 14)]], {})}),
        ),
    ]
