# Generated by Django 5.2.6 on 2026-02-21 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_homepage_hero_promise'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_index',
            field=models.ForeignKey(blank=True, help_text='Sélectionne la page Blog (index) pour tirer les articles récents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
