# Generated by Django 5.2.6 on 2025-09-26 10:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformpage',
            name='consent_required',
            field=models.BooleanField(default=True, help_text='Si activé, la case doit être cochée pour soumettre le formulaire.', verbose_name='Consentement obligatoire'),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='consent_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Message de consentement affiché sous les champs (ex. RGPD/marketing).'),
        ),
    ]
