# Generated by Django 5.2.6 on 2025-09-26 12:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_featured_blogpage_image_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=wagtail.fields.RichTextField(),
        ),
    ]
