# Generated by Django 5.2.6 on 2025-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_blogpage_categories_blogpagetag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Si coché, l’article peut apparaître dans le bandeau À la une.', verbose_name='Mettre à la une'),
        ),
    ]
