# Generated by Django 5.2.6 on 2026-02-21 21:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.StreamField([('paragraphe', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('duree', models.CharField(blank=True, max_length=50)),
                ('public_cible', models.CharField(blank=True, max_length=255)),
                ('objectif', wagtail.fields.RichTextField(blank=True)),
                ('prerequis', wagtail.fields.RichTextField(blank=True)),
                ('programme', wagtail.fields.RichTextField(blank=True)),
                ('niveau', models.CharField(choices=[('decouverte', 'Découverte'), ('pratique', 'Pratique'), ('technique', 'Technique'), ('expert', 'Expert')], default='decouverte', max_length=50)),
                ('modalite', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], default='presentiel', max_length=50)),
                ('prix_individuel', models.CharField(blank=True, help_text='Ex: 150 000 FCFA', max_length=50)),
                ('prix_entreprise', models.CharField(blank=True, help_text='Ex: 2 200 000 FCFA ou Sur devis', max_length=50)),
                ('inclus', wagtail.fields.RichTextField(blank=True, help_text='Optionnel : supports, attestation, coaching, etc.')),
                ('cta_label', models.CharField(blank=True, default='Demander cette formation', max_length=80)),
                ('cta_url', models.URLField(blank=True)),
                ('cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
