# Generated by Django 5.2.6 on 2026-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_formationrequestpage_demandeformationformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeformationformfield',
            name='is_readonly',
            field=models.BooleanField(default=False, verbose_name='Lecture seule (readonly)'),
        ),
    ]
