# Generated by Django 5.2.6 on 2026-02-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_demandeformationformfield_is_readonly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeformationformfield',
            name='is_readonly',
        ),
    ]
