# Generated by Django 5.2.6 on 2026-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groupes autorisés à télécharger (vide = accessible à tout utilisateur connecté).', related_name='allowed_documents', to='auth.group'),
        ),
    ]
