# Generated by Django 5.2.6 on 2025-09-27 16:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='À propos', max_length=100)),
                ('about_text', wagtail.fields.RichTextField(blank=True, default='DIBOS est un projet collaboratif visant à valoriser les talents et l’innovation au Congo.')),
                ('links_title', models.CharField(default='Liens utiles', max_length=100)),
                ('links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texte du lien', 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Lien vers une page interne', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': '…ou URL externe', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}, default=[])),
                ('social_title', models.CharField(default='Suivez-nous', max_length=100)),
                ('socials', wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nom du réseau (Facebook, X/Twitter, LinkedIn…)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classe Bootstrap Icons (ex: bi bi-facebook)', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('icon_class', 1), ('url', 2)]], {})}, default=[])),
                ('footer_bg_class', models.CharField(default='bg-navy', help_text='Classe CSS de fond (ex: bg-navy ou bg-dark)', max_length=100)),
                ('footer_text_class', models.CharField(default='text-light', help_text='Classe CSS du texte (ex: text-light)', max_length=100)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer (paramètres du site)',
            },
        ),
    ]
