# Generated by Django 5.2.6 on 2026-02-08 08:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, default='Kerenes est un projet collaboratif visant à valoriser les talents et l’innovation au Congo.'),
        ),
    ]
